### PR TITLE
fix(env): make errors from environment clearer

### LINKED ISSUE #114: Necessary environment variables are not clear
Right now, when the bot crashes due to missing environment variables, the user ends up with a cryptic zod error.
It's quite hard to understand which environment variables are missing.

### PR DESCRIPTION
**Pull request by potb**
Closes #114

### CODE REVIEW

File: src/core/createEnvForModule.ts [hunk 1]
```diff
@@ -18,14 +18,14 @@ const createEnvForModule = (constantName: string) =>
     }, {});
 
 export const createAllModules = async (
-  modules: Record<string, ModuleFactory>,
+  modules: Record<string, ModuleCreator>,
 ): Promise<CreatedModule[]> => {
   const createdModules: CreatedModule[] = [];
 
-  for (const [name, factory] of Object.entries(modules)) {
+  for (const { name, factory } of Object.values(modules)) {
```
Comment (luca-montaigut) [inline src/core/createEnvForModule.ts:25]: I think we need a check here to avoid multiple module with the same name, WDYT ?

Comment (potb) [reply src/core/createEnvForModule.ts:25]: Indeed, I'd suggest you create an issue for that and we deal with it later.

**Review by luca-montaigut — APPROVED** [review]
